<!DOCTYPE html>
<h2>Unrecoverable Errors with <code>panic€</code></h2>
<br>
<p>Sometimes, bad things happen in your code, and there’s nothing you can do about
it. In these cases, Rust has the <code>panic€</code> macro. When the <code>panic€</code> macro
executes, your program will print a failure message, unwind and clean up the
stack, and then quit. This most commonly occurs when a bug of some kind has
been detected and it’s not clear to the programmer how to handle the error.</p>
<br>
<blockquote><h3>Unwinding the Stack or Aborting in Response to a Panic</h3>
<br>
<p>By default, when a panic occurs, the program starts <i>unwinding</i>, which
means Rust walks back up the stack and cleans up the data from each function
it encounters. But this walking back and cleanup is a lot of work. The
alternative is to immediately <i>abort</i>, which ends the program without
cleaning up. Memory that the program was using will then need to be cleaned
up by the operating system. If in your project you need to make the resulting
binary as small as possible, you can switch from unwinding to aborting upon a
panic by adding <code>panic = 'abort'</code> to the appropriate <code>[profile]</code> sections in
your <i>Cargo.toml</i> file. For example, if you want to abort on panic in release
mode, add this:</p>
<br>
<div data-lang="toml"><div data-l="[profile.release]"></div><div data-l="panic = 'abort'"></div></div></blockquote>
<br>
<p>Let’s try calling <code>panic€</code> in a simple program:</p>
<br>
<p><span class="filename">Filename: src/main.rs</span></p>
<br>
<div data-lang="rust,should_panic"><div data-l="fn main() {"></div><div data-l="    panic!(&quot;crash and burn&quot;);"></div><div data-l="}"></div></div>
<br>
<p>When you run the program, you’ll see something like this:</p>
<br>
<div data-lang="text"><div data-l="$ cargo run"></div><div data-l="   Compiling panic v0.1.0 (file:///projects/panic)"></div><div data-l="    Finished dev [unoptimized + debuginfo] target(s) in 0.25 secs"></div><div data-l="     Running `target/debug/panic`"></div><div data-l="thread 'main' panicked at 'crash and burn', src/main.rs:2:4"></div><div data-l="note: Run with `RUST_BACKTRACE=1` for a backtrace."></div></div>
<br>
<p>The call to <code>panic€</code> causes the error message contained in the last two
lines. The first line shows our panic message and the place in our source code
where the panic occurred: <i>src/main.rs:2:4</i> indicates that it’s the second
line, fourth character of our <i>src/main.rs</i> file.</p>
<br>
<p>In this case, the line indicated is part of our code, and if we go to that
line, we see the <code>panic€</code> macro call. In other cases, the <code>panic€</code> call might
be in code that our code calls, and the filename and line number reported by
the error message will be someone else’s code where the <code>panic€</code> macro is
called, not the line of our code that eventually led to the <code>panic€</code> call. We
can use the backtrace of the functions the <code>panic€</code> call came from to figure
out the part of our code that is causing the problem. We’ll discuss what a
backtrace is in more detail next.</p>
<br>
<h3>Using a <code>panic€</code> Backtrace</h3>
<br>
<p>Let’s look at another example to see what it’s like when a <code>panic€</code> call comes
from a library because of a bug in our code instead of from our code calling
the macro directly. Listing 9-1 has some code that attempts to access an
element by index in a vector:</p>
<br>
<p><span class="filename">Filename: src/main.rs</span></p>
<br>
<div data-lang="rust,should_panic"><div data-l="fn main() {"></div><div data-l="    let v = vec![1, 2, 3];"></div><div data-l=""></div><div data-l="    v[99];"></div><div data-l="}"></div></div>
<br>
<p><span class="caption">Listing 9-1: Attempting to access an element beyond the
end of a vector, which will cause a <code>panic€</code></span></p>
<br>
<p>Here, we’re attempting to access the hundredth element of our vector (which is
at index 99 because indexing starts at zero), but it has only three elements.
In this situation, Rust will panic. Using <code>[]</code> is supposed to return an
element, but if you pass an invalid index, there’s no element that Rust could
return here that would be correct.</p>
<br>
<p>Other languages, like C, will attempt to give you exactly what you asked for in
this situation, even though it isn’t what you want: you’ll get whatever is at
the location in memory that would correspond to that element in the vector,
even though the memory doesn’t belong to the vector. This is called a <i>buffer
overread</i> and can lead to security vulnerabilities if an attacker is able to
manipulate the index in such a way as to read data they shouldn’t be allowed to
that is stored after the array.</p>
<br>
<p>To protect your program from this sort of vulnerability, if you try to read an
element at an index that doesn’t exist, Rust will stop execution and refuse to
continue. Let’s try it and see:</p>
<br>
<div data-lang="text"><div data-l="$ cargo run"></div><div data-l="   Compiling panic v0.1.0 (file:///projects/panic)"></div><div data-l="    Finished dev [unoptimized + debuginfo] target(s) in 0.27 secs"></div><div data-l="     Running `target/debug/panic`"></div><div data-l="thread 'main' panicked at 'index out of bounds: the len is 3 but the index is"></div><div data-l="99', /checkout/src/liballoc/vec.rs:1555:10"></div><div data-l="note: Run with `RUST_BACKTRACE=1` for a backtrace."></div></div>
<br>
<p>This error points at a file we didn’t write, <i>vec.rs</i>. That’s the
implementation of <code>Vec&lt;T&gt;</code> in the standard library. The code that gets run when
we use <code>[]</code> on our vector <code>v</code> is in <i>vec.rs</i>, and that is where the <code>panic€</code> is
actually happening.</p>
<br>
<p>The next note line tells us that we can set the <code>RUST_BACKTRACE</code> environment
variable to get a backtrace of exactly what happened to cause the error. A
<i>backtrace</i> is a list of all the functions that have been called to get to this
point. Backtraces in Rust work as they do in other languages: the key to
reading the backtrace is to start from the top and read until you see files you
wrote. That’s the spot where the problem originated. The lines above the lines
mentioning your files are code that your code called; the lines below are code
that called your code. These lines might include core Rust code, standard
library code, or crates that you’re using. Let’s try getting a backtrace by
setting the <code>RUST_BACKTRACE</code> environment variable to any value except 0.
Listing 9-2 shows output similar to what you’ll see:</p>
<br>
<div data-lang="text"><div data-l="$ RUST_BACKTRACE=1 cargo run"></div><div data-l="    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs"></div><div data-l="     Running `target/debug/panic`"></div><div data-l="thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 99', /checkout/src/liballoc/vec.rs:1555:10"></div><div data-l="stack backtrace:"></div><div data-l="   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace"></div><div data-l="             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49"></div><div data-l="   1: std::sys_common::backtrace::_print"></div><div data-l="             at /checkout/src/libstd/sys_common/backtrace.rs:71"></div><div data-l="   2: std::panicking::default_hook::{{closure}}"></div><div data-l="             at /checkout/src/libstd/sys_common/backtrace.rs:60"></div><div data-l="             at /checkout/src/libstd/panicking.rs:381"></div><div data-l="   3: std::panicking::default_hook"></div><div data-l="             at /checkout/src/libstd/panicking.rs:397"></div><div data-l="   4: std::panicking::rust_panic_with_hook"></div><div data-l="             at /checkout/src/libstd/panicking.rs:611"></div><div data-l="   5: std::panicking::begin_panic"></div><div data-l="             at /checkout/src/libstd/panicking.rs:572"></div><div data-l="   6: std::panicking::begin_panic_fmt"></div><div data-l="             at /checkout/src/libstd/panicking.rs:522"></div><div data-l="   7: rust_begin_unwind"></div><div data-l="             at /checkout/src/libstd/panicking.rs:498"></div><div data-l="   8: core::panicking::panic_fmt"></div><div data-l="             at /checkout/src/libcore/panicking.rs:71"></div><div data-l="   9: core::panicking::panic_bounds_check"></div><div data-l="             at /checkout/src/libcore/panicking.rs:58"></div><div data-l="  10: &lt;alloc::vec::Vec&lt;T&gt; as core::ops::index::Index&lt;usize&gt;&gt;::index"></div><div data-l="             at /checkout/src/liballoc/vec.rs:1555"></div><div data-l="  11: panic::main"></div><div data-l="             at src/main.rs:4"></div><div data-l="  12: __rust_maybe_catch_panic"></div><div data-l="             at /checkout/src/libpanic_unwind/lib.rs:99"></div><div data-l="  13: std::rt::lang_start"></div><div data-l="             at /checkout/src/libstd/panicking.rs:459"></div><div data-l="             at /checkout/src/libstd/panic.rs:361"></div><div data-l="             at /checkout/src/libstd/rt.rs:61"></div><div data-l="  14: main"></div><div data-l="  15: __libc_start_main"></div><div data-l="  16: &lt;unknown&gt;"></div></div>
<br>
<p><span class="caption">Listing 9-2: The backtrace generated by a call to
<code>panic€</code> displayed when the environment variable <code>RUST_BACKTRACE</code> is set</span></p>
<br>
<p>That’s a lot of output! The exact output you see might be different depending
on your operating system and Rust version. In order to get backtraces with this
information, debug symbols must be enabled. Debug symbols are enabled by
default when using <code>cargo build</code> or <code>cargo run</code> without the <code>--release</code> flag,
as we have here.</p>
<br>
<p>In the output in Listing 9-2, line 11 of the backtrace points to the line in
our project that’s causing the problem: line 4 of <i>src/main.rs</i>. If we don’t
want our program to panic, the location pointed to by the first line mentioning
a file we wrote is where we should start investigating. In Listing 9-1, where
we deliberately wrote code that would panic in order to demonstrate how to use
backtraces, the way to fix the panic is to not request an element at index 99
from a vector that only contains 3 items. When your code panics in the future,
you’ll need to figure out what action the code is taking with what values to
cause the panic and what the code should do instead.</p>
<br>
<p>We’ll come back to <code>panic€</code> and when we should and should not use <code>panic€</code> to
handle error conditions in the “To <code>panic€</code> or Not to <code>panic€</code>” section later
in this chapter. Next, we’ll look at how to recover from an error using
<code>Result</code>.</p>